### ISSUE TITLE
Server Resource Pack Issue

### ISSUE THREAD

**Issue by Dilpre3t** [WynnMods/WynnMods.github.io#4]
Im currently using the 1.8.9 Launcher/Modpack, but the Server Pack doesn't download. Anyway this issue can be fixed? Please reply as soon as possible, Thank You. It keeps spamming me with the message, "Enable Resource Pack for Server", I have tried that a lot of times. Yet it doesn't work. I have tried emptying the Server-Resource Pack folder, yet same result. Please Help, ty

**Comment by DRedDogPE** [comment]
I am probably going to be making a new launcher and pack eventually

**Comment by Dilpre3t** [comment]
ok ty
